### ISSUE TITLE
[audit] Returning 0 as hashed_domain when resolving through a resolver.

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/naming#47]
In the resolve_util(...) function, if the resolver contract exists, it returns 0 for the hashed_domain. This isn’t a recommended practice.

Let's find a way to make sure that if the resolver contract returns 0, we compute the hashed_domain (if the resolver wants to avoid this, he should panics)

**Comment by irisdv** [comment]
I'm not sure to understand this issue @Th0rgal . Should we return the `hashed_domain` instead of 0 if there is resolver that is found ? because if no `resolver` is found, we will always compute the `hashed_domain`.
