### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Th0rgal** [starknet-id/naming#5]
Can be done:
- Porting existing tests
- Increasing test coverage to cover more scenarii
- Indexing new events (and adding missing ones)
- optimizing (some domain hashes are computed too many times, using #inline could help)
- check storage compatibility

Need to update Cairo (but too slow atm):
- move events out of the main file
- relying on components for inheriting things like upgradability

**Comment by Mohiiit** [comment]
Hey, Can I contribute?
